# Generated by Django 5.2.7 on 2025-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='requested_by',
        ),
        migrations.AlterField(
            model_name='request',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
